### ISSUE TITLE
Editorial comments

### ISSUE THREAD

**Issue by liljenstolpe** [Metaswitch/calico-docs#2]
There are a number of places where ' , ' and ' . ' occurs.

There's an incomplete sentence:  Then, when an IPv4 packet is received by the compute host on one of those TAP interfaces, it can be translated to an IPv6 packet whose addresses contain the correct .

We don't need the fabric to be IPv6 only.  In fact, since this is a corner case, we would still assume that most traffic that isn't in overlapped space (i.e. centrally assigned) would be in the default routing name space, and be transported natively.  We would only use the 464 for overlapped (private) uses of IPv4.

We may use name spaces for the 464 link to TAYGA, or we may just be able to use a policy via ipchains?

Also, would https://github.com/toreanderson/clatd help as a clat function?

**Comment by Lukasa** [comment]
I take it that this is all commentary on the 464XLAT doc, in which case this belongs to @neiljerram.

**Comment by neiljerram** [comment]
Thanks @liljenstolpe, I've fixed the editorial points now - all caused by failing to escape the angle brackets around "ID".

I'll leave this issue open for the chunkier points you've raised.  I have some other doc in progress that may help there....
